[package]
name = "quantinuum-hugr"
version = "0.1.0"
license = "Apache-2.0"

readme = "README.md"
#documentation = "https://docs.rs/hugr/"
repository = "https://github.com/CQCL/hugr"

description = "Hierarchical Unified Graph Representation"
#keywords = [] # TODO
#categories = [] # TODO

edition = "2021"
rust-version = "1.69"

[lib]
# Using different names for the lib and for the package is supported, but may be confusing.
# https://github.com/rust-lang/cargo/issues/6827
# TODO: Should we rename one of them?
name = "hugr"
bench = false
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.28"
portgraph = { version = "0.2.0", features = ["serde"] }
pyo3 = { version = "0.18.1", optional = true, features = [
    "multiple-pymethods",
] }
cgmath = { version = "0.18.0", features = ["serde"] }
num-rational = { version = "0.4.1", features = ["serde"] }
downcast-rs = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.19"
once_cell = "1.17.1"
typetag = "0.2.7"
smol_str = {version = "0.1.24", features = ["serde"]}
derive_more = "0.99.17"
itertools = "0.10.5"

[features]
pyo3 = ["dep:pyo3"]

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
rstest = "0.17.0"
portgraph = { version = "0.2.0", features = ["proptest"] }
proptest = "1.1.0"
rmp-serde = "1.1.1"
webbrowser = "0.8.10"
url-escape = "0.1.1"
cool_asserts = "2.0.3"

[[bench]]
name = "bench_main"
harness = false
